service: nodejs-lambda-sample

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
