service: nodejs-lambda-sample

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

custom:
  libLayerArn: arn:aws:lambda:${self:provider.region}:${aws:accountId}:layer:nodejs-layer-test:1

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    layers:
      - ${self:custom.libLayerArn}
    events:
      - httpApi:
          path: /
          method: get
